name: micro-deis
home: https://github.com/krancour/micro-deis
version: 2.0.0-alpha
description: For testing only!
maintainers:
- Kent Rancourt <kent.rancourt@gmail.com>
details: |-
  WARNING: this chart is for testing only! Features may not work, the
  components are not HA, and there are likely to be bugs.

  Deis (pronounced DAY-iss) is an open source PaaS that makes it easy to deploy
  and manage applications on your own servers. Deis builds on Kubernetes
  to provide a lightweight, Heroku-inspired workflow.
